version: '3'

services:
  php:
    container_name: ${DOCKER_NAMESPACE}-php
    build:
      context: ./docker/php
      args:
        uid: ${DOCKER_UID}
    volumes:
      - ./:/srv/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
  nginx:
    container_name: ${DOCKER_NAMESPACE}-nginx
    image: nginx:latest
    ports:
      - ${DOCKER_HTTP_PORT}:80
    volumes:
      - ./:/srv/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    container_name: ${DOCKER_NAMESPACE}-mysql
    image: mysql:8.0.17
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
